# Select the box
box: ubuntu/trusty64

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

swapsize: 1024

# Guest OS timezone
timezone: Europe/London

# Virtual machine name
machine_name: default

# Virtual machine IP
ip: 192.168.83.137

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 512

#applicaltion domail
domain: basic.dev

# Your personal GitHub token
github_token: <your-personal-github-token>
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens